name: Datapack Bug Report
description: Submit a datapack bug report.
title: "[pack] "
labels: 
- "bug :bug:"
assignees:
- legopitstop
body:
 - type: markdown
   attributes:
     value: |
      Note: Please search to see if an issue already exists for the bug you encountered.

 - type: dropdown
   id: datapack
   validations:
     required: true
   attributes:
     label: What Datapack are you using?
     description: The Datapack  where the issue is taking place
     multiple: false
     options:
       - Armorstand Poses
       - Bandage
       - Barked
       - Better Item Frames
       - Botanic Pots
       - Camera View
       - Coal Under Pressure
       - Convert Traders
       - Craftable Chainmail
       - Item Display
       - LPS Recipe API
       - Lightning Bolt Glass
       - Minecoin
       - More Flower Pots
       - More Honey
       - More Music
       - More Redstone
       - Moveable Tiles
       - Place on Head
       - Simple Calculator
       - Spawner Craft
       - Splashable Concrete
       - Trumpet Skeleton
       - Unlit Campfire
       - Vending Machine
       - Effect Charms (Deprived)
       - More Buckets (Deprived)
       - Server Bossbar (Deprived)
       - Christmas Presents (Deprived)
       - Bluestone (Deprived)
       - Advanced Farming (Deprived)
       - Invisable Item Frames (Deprived) (Merged with Better Item Frames)
       - CCW Item Frames (Merged with Better Item Frames)
       - Other

 - type: textarea
   id: describe
   validations:
     required: true
   attributes:
     label: Describe the bug
     description: A clear and concise description of what the bug is.

 - type: textarea
   id: reproduce
   validations:
     required: true
   attributes:
     label: Steps To Reproduce
     description: Steps to reproduce the behavior
     value: |
      1.
      2.
      3.
      ...


 - type: textarea
   id: expected
   validations:
     required: true
   attributes:
     label: Expected behavior
     description: A clear and concise description of what you expected to happen.

 - type: input
   id: minecraft_version
   validations:
     required: true
   attributes:
     label: Minecraft Version
     description: The version of Minecraft that you are using this mod on.
     placeholder: e.g. 1.18.2

 - type: input
   id: datapack_version
   validations:
     required: true
   attributes:
     label: Datapack Version
     description: The version of the Datapack that you are using.
     placeholder: e.g. 1.0.0

 - type: input
   id: platform
   attributes:
     label: Platform
     description: The device that you are using this mod on. 
     placeholder: e.g. Windows 11, Linux, MacOS

 - type: textarea
   id: other
   attributes:
     label: Additional context
     description: |
      Add any other information about the problem here.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

